name: xyz
description: xyz

version: 1.0.0+1

environment:
  sdk: ">2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.16.1
  provider: ^4.1.0-dev+3

flutter:

  # include Material icons with application
  uses-material-design: true

#  assets:

#  fonts:
